### ISSUE TITLE
Query:  Adding a default conversation

### ISSUE THREAD

**Issue by EcoChampions** [realm/RChat#15]
I want to be able to add each user to a "default" conversation such that every user starts with at least one conversation (with no team members).  Sounds crazy but I want to go and build out further but need to grasp the basics first!

I have literally spent HOURS trying lots of different options.  Please help before I go completely crazy!  My latest attempt being as follows:

 // Open the default realm
        let realm = try! Realm()
        
        try! realm.write {
            let conversation = Conversation()
            conversation.displayName = "My Conversation"
            conversation.unreadCount = 0
        
            var user = app.currentUser
            let userID = user.id
            
            let thisUser = User(_id: userID)
            realm.add(user)
        }

**Comment by am-MongoDB** [comment]
A couple of comments on this code....

1. Only the `realm.add` needs to be within the `realm.write` transaction.
2. You're not adding `conversation` to `thisUser`
3. You should be adding `thisUser` (rather than `user`) to your realm

**Comment by EcoChampions** [comment]
Thanks Andrew. I was trying to also add conversation: conversation to the user as well but can't get beyond getting it to recognise the user id. Also I'm thinking I shouldn't be adding rather than updating the existing user but can't figure out the syntax. Sorry for the silly questions but found your example very informative and trying to play with it to develop my knowledge of swift and realm
