### ISSUE TITLE
Chat integration with task app

### ISSUE THREAD

**Issue by alelordelo** [realm/RChat#23]
Hi @am-MongoDB,

I am trying to integrate the chat app with the real task app, so that each task can have a group discussion (like in Asana or Trello).
Could you give an insight on how the overall model would look like to make both work together?

Cheers
Alex

**Comment by am-MongoDB** [comment]
Hi @alelordelo 

I don't think that too many changes to the schema would be needed. In the [ChatMessage](https://github.com/realm/RChat/blob/main/RChat-iOS/RChat/Model/ChatMessage.swift) Object, I'd still have....

```swift
 @Persisted var partition = "" // "conversation=<conversation-id>"
``` 

but `<conversation-id>` would be the id of the Task object.

Cheers, Andrew.
