### ISSUE TITLE
Blank screen on registering a new user but okay on first Login

### ISSUE THREAD

**Issue by sandhums** [realm/RChat#26]
@am-MongoDB 
Thank you for such a helpful walk around Realm and SwiftUI
I am trying out your chat app - flex sync version
Am experiencing a blank screen when registering a new user , but when the user logs in again the ConversationList View is shown.
Any help on this?
Thanks

**Comment by am-MongoDB** [comment]
Hi @sandhums – could you try changing the realm-swift package version to `10.25.2`? Delete the app from the simulator before loading on the new version

**Comment by sandhums** [comment]
Thank you for the tip.
Will try and let you know.

Warm Regards

Dr (Col) Manjinder Sandhu
MD, DNB, DM, FSCAI, FACC, MHA
Director Cardiology and Artemis Cardiac Care Pvt Ltd

http://www.artemishospitals.com/

________________________________

**Comment by sandhums** [comment]
Yes, it worked after changing to 10.25.2, Thank you
